ALTER TABLE "CarpoolOrder" ADD COLUMN IF NOT EXISTS "deletedByCustomer" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CarpoolOrder" ADD COLUMN IF NOT EXISTS "deletedByDriver" BOOLEAN NOT NULL DEFAULT false;
